version: 1
services:
  - type: web
    name: yt_to_mp3
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"  # Ganti dengan nama file dan objek Flask-mu
